name: GitHub CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Backend/API/API.csproj
      
    - name: Build with DotNet
      run: dotnet build --no-restore ./Backend/API/API.csproj
      
    - name: Run UnitTest
      run: dotnet test ./Backend/UnitTests/UnitTests.csproj
      
    - name: Run IntegrationTest
      run: dotnet test ./Backend/IntegrationTests/IntegrationTests.csproj
