name: GitHub CI Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
